// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_500 from './routes/_500.tsx'
import * as $_app from './routes/_app.tsx'
import * as $index from './routes/index.tsx'
import * as $ingresar from './routes/ingresar.tsx'
import * as $proyecto_idProyecto_anuncio_idAnuncio_eliminar from './routes/proyecto/[idProyecto]/anuncio/[idAnuncio]/eliminar.ts'
import * as $proyecto_idProyecto_anuncio_middleware from './routes/proyecto/[idProyecto]/anuncio/_middleware.ts'
import * as $proyecto_idProyecto_anuncio_crear from './routes/proyecto/[idProyecto]/anuncio/crear.tsx'
import * as $proyecto_idProyecto_editar_middleware from './routes/proyecto/[idProyecto]/editar/_middleware.ts'
import * as $proyecto_idProyecto_editar_index from './routes/proyecto/[idProyecto]/editar/index.tsx'
import * as $proyecto_idProyecto_eliminar_middleware from './routes/proyecto/[idProyecto]/eliminar/_middleware.ts'
import * as $proyecto_idProyecto_eliminar_index from './routes/proyecto/[idProyecto]/eliminar/index.tsx'
import * as $proyecto_idProyecto_equipo from './routes/proyecto/[idProyecto]/equipo.tsx'
import * as $proyecto_idProyecto_index from './routes/proyecto/[idProyecto]/index.tsx'
import * as $proyecto_idProyecto_tareas_idTarea_index from './routes/proyecto/[idProyecto]/tareas/[idTarea]/index.tsx'
import * as $proyecto_idProyecto_tareas_crear from './routes/proyecto/[idProyecto]/tareas/crear.tsx'
import * as $proyecto_middleware from './routes/proyecto/_middleware.ts'
import * as $registro from './routes/registro.tsx'
import * as $salir from './routes/salir.ts'
import * as $usuario_middleware from './routes/usuario/_middleware.ts'
import * as $usuario_admin_middleware from './routes/usuario/admin/_middleware.ts'
import * as $usuario_admin_crear_proyecto from './routes/usuario/admin/crear-proyecto.tsx'
import * as $usuario_admin_index from './routes/usuario/admin/index.tsx'
import * as $usuario_configuracion from './routes/usuario/configuracion.tsx'
import * as $usuario_editar_contrasena from './routes/usuario/editar/contrasena.ts'
import * as $usuario_editar_nombre from './routes/usuario/editar/nombre.ts'
import * as $usuario_editar_tema from './routes/usuario/editar/tema.ts'
import * as $usuario_miembro_middleware from './routes/usuario/miembro/_middleware.ts'
import * as $usuario_miembro_index from './routes/usuario/miembro/index.tsx'
import * as $usuario_notificaciones from './routes/usuario/notificaciones.tsx'
import * as $Counter from './islands/Counter.tsx'
import * as $Modal from './islands/Modal.tsx'
import * as $NavBar from './islands/NavBar.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_500.tsx': $_500,
    './routes/_app.tsx': $_app,
    './routes/index.tsx': $index,
    './routes/ingresar.tsx': $ingresar,
    './routes/proyecto/[idProyecto]/anuncio/[idAnuncio]/eliminar.ts': $proyecto_idProyecto_anuncio_idAnuncio_eliminar,
    './routes/proyecto/[idProyecto]/anuncio/_middleware.ts': $proyecto_idProyecto_anuncio_middleware,
    './routes/proyecto/[idProyecto]/anuncio/crear.tsx': $proyecto_idProyecto_anuncio_crear,
    './routes/proyecto/[idProyecto]/editar/_middleware.ts': $proyecto_idProyecto_editar_middleware,
    './routes/proyecto/[idProyecto]/editar/index.tsx': $proyecto_idProyecto_editar_index,
    './routes/proyecto/[idProyecto]/eliminar/_middleware.ts': $proyecto_idProyecto_eliminar_middleware,
    './routes/proyecto/[idProyecto]/eliminar/index.tsx': $proyecto_idProyecto_eliminar_index,
    './routes/proyecto/[idProyecto]/equipo.tsx': $proyecto_idProyecto_equipo,
    './routes/proyecto/[idProyecto]/index.tsx': $proyecto_idProyecto_index,
    './routes/proyecto/[idProyecto]/tareas/[idTarea]/index.tsx': $proyecto_idProyecto_tareas_idTarea_index,
    './routes/proyecto/[idProyecto]/tareas/crear.tsx': $proyecto_idProyecto_tareas_crear,
    './routes/proyecto/_middleware.ts': $proyecto_middleware,
    './routes/registro.tsx': $registro,
    './routes/salir.ts': $salir,
    './routes/usuario/_middleware.ts': $usuario_middleware,
    './routes/usuario/admin/_middleware.ts': $usuario_admin_middleware,
    './routes/usuario/admin/crear-proyecto.tsx': $usuario_admin_crear_proyecto,
    './routes/usuario/admin/index.tsx': $usuario_admin_index,
    './routes/usuario/configuracion.tsx': $usuario_configuracion,
    './routes/usuario/editar/contrasena.ts': $usuario_editar_contrasena,
    './routes/usuario/editar/nombre.ts': $usuario_editar_nombre,
    './routes/usuario/editar/tema.ts': $usuario_editar_tema,
    './routes/usuario/miembro/_middleware.ts': $usuario_miembro_middleware,
    './routes/usuario/miembro/index.tsx': $usuario_miembro_index,
    './routes/usuario/notificaciones.tsx': $usuario_notificaciones,
  },
  islands: {
    './islands/Counter.tsx': $Counter,
    './islands/Modal.tsx': $Modal,
    './islands/NavBar.tsx': $NavBar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
