// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $a_middleware from './routes/a/_middleware.ts'
import * as $a_admin_middleware from './routes/a/admin/_middleware.ts'
import * as $a_admin_crear_proyecto from './routes/a/admin/crear-proyecto.tsx'
import * as $a_configuracion from './routes/a/configuracion.tsx'
import * as $a_editar_contrasena from './routes/a/editar/contrasena.ts'
import * as $a_editar_nombre from './routes/a/editar/nombre.ts'
import * as $a_editar_tema from './routes/a/editar/tema.ts'
import * as $a_index from './routes/a/index.tsx'
import * as $a_notificaciones from './routes/a/notificaciones.tsx'
import * as $a_proyectos_idProyecto_anuncio_idAnuncio_eliminar from './routes/a/proyectos/[idProyecto]/anuncio/[idAnuncio]/eliminar.ts'
import * as $a_proyectos_idProyecto_anuncio_middleware from './routes/a/proyectos/[idProyecto]/anuncio/_middleware.ts'
import * as $a_proyectos_idProyecto_anuncio_crear from './routes/a/proyectos/[idProyecto]/anuncio/crear.tsx'
import * as $a_proyectos_idProyecto_editar from './routes/a/proyectos/[idProyecto]/editar.tsx'
import * as $a_proyectos_idProyecto_eliminar from './routes/a/proyectos/[idProyecto]/eliminar.tsx'
import * as $a_proyectos_idProyecto_equipo from './routes/a/proyectos/[idProyecto]/equipo.tsx'
import * as $a_proyectos_idProyecto_index from './routes/a/proyectos/[idProyecto]/index.tsx'
import * as $a_proyectos_idProyecto_tareas_idTarea_completar from './routes/a/proyectos/[idProyecto]/tareas/[idTarea]/completar.ts'
import * as $a_proyectos_idProyecto_tareas_idTarea_editar from './routes/a/proyectos/[idProyecto]/tareas/[idTarea]/editar.tsx'
import * as $a_proyectos_idProyecto_tareas_idTarea_eliminar from './routes/a/proyectos/[idProyecto]/tareas/[idTarea]/eliminar.tsx'
import * as $a_proyectos_idProyecto_tareas_idTarea_index from './routes/a/proyectos/[idProyecto]/tareas/[idTarea]/index.tsx'
import * as $a_proyectos_idProyecto_tareas_crear from './routes/a/proyectos/[idProyecto]/tareas/crear.tsx'
import * as $index from './routes/index.tsx'
import * as $ingresar from './routes/ingresar.tsx'
import * as $registro from './routes/registro.tsx'
import * as $salir from './routes/salir.ts'
import * as $Modal from './islands/Modal.tsx'
import * as $NavBar from './islands/NavBar.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/a/_middleware.ts': $a_middleware,
    './routes/a/admin/_middleware.ts': $a_admin_middleware,
    './routes/a/admin/crear-proyecto.tsx': $a_admin_crear_proyecto,
    './routes/a/configuracion.tsx': $a_configuracion,
    './routes/a/editar/contrasena.ts': $a_editar_contrasena,
    './routes/a/editar/nombre.ts': $a_editar_nombre,
    './routes/a/editar/tema.ts': $a_editar_tema,
    './routes/a/index.tsx': $a_index,
    './routes/a/notificaciones.tsx': $a_notificaciones,
    './routes/a/proyectos/[idProyecto]/anuncio/[idAnuncio]/eliminar.ts':
      $a_proyectos_idProyecto_anuncio_idAnuncio_eliminar,
    './routes/a/proyectos/[idProyecto]/anuncio/_middleware.ts': $a_proyectos_idProyecto_anuncio_middleware,
    './routes/a/proyectos/[idProyecto]/anuncio/crear.tsx': $a_proyectos_idProyecto_anuncio_crear,
    './routes/a/proyectos/[idProyecto]/editar.tsx': $a_proyectos_idProyecto_editar,
    './routes/a/proyectos/[idProyecto]/eliminar.tsx': $a_proyectos_idProyecto_eliminar,
    './routes/a/proyectos/[idProyecto]/equipo.tsx': $a_proyectos_idProyecto_equipo,
    './routes/a/proyectos/[idProyecto]/index.tsx': $a_proyectos_idProyecto_index,
    './routes/a/proyectos/[idProyecto]/tareas/[idTarea]/completar.ts': $a_proyectos_idProyecto_tareas_idTarea_completar,
    './routes/a/proyectos/[idProyecto]/tareas/[idTarea]/editar.tsx': $a_proyectos_idProyecto_tareas_idTarea_editar,
    './routes/a/proyectos/[idProyecto]/tareas/[idTarea]/eliminar.tsx': $a_proyectos_idProyecto_tareas_idTarea_eliminar,
    './routes/a/proyectos/[idProyecto]/tareas/[idTarea]/index.tsx': $a_proyectos_idProyecto_tareas_idTarea_index,
    './routes/a/proyectos/[idProyecto]/tareas/crear.tsx': $a_proyectos_idProyecto_tareas_crear,
    './routes/index.tsx': $index,
    './routes/ingresar.tsx': $ingresar,
    './routes/registro.tsx': $registro,
    './routes/salir.ts': $salir,
  },
  islands: {
    './islands/Modal.tsx': $Modal,
    './islands/NavBar.tsx': $NavBar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
